### ISSUE TITLE
error on first load

### ISSUE THREAD

**Issue by Cromaxxx** [failcoder/SVUI-Kit#7]
http://i.imgur.com/4yC6QcO.jpg

**Comment by failcoder** [comment]
That was an UNSTABLE version, if it's ready for you guys to download again I will either respond to one of your issue here on github or I will make a post on WowInterface. typically I upload MANY times throughout the day but most of them are from "blind" coding sessions which makes them very broken but I need to push so that I can grab the code again from a different physical location. I suppose I should just use a thumbdrive but.... im not well in the head!

**Comment by failcoder** [comment]
On that subject.... it's ready for you to download again. LOL

**Comment by Cromaxxx** [comment]
its not problem when you do fast fixes .. i like to help if i can

**Comment by failcoder** [comment]
And I definitely appreciate that
